Add "Unverified" Servers
EchoTools/EchoRelay pull request #2
Opened 2023-11-06 19:30 UTC by UnusualNorm

If enabled, this allows anyone to connect a server to your relay instance with an "unverified" flag. Users will only be able to utilize these unverified servers by enabling the "unverifiedservers" matching parameter in their config. Ideally, this should be used to help determine who to trust with hosting verified servers by receiving feedback about uptime and lag from users who are willing to risk the potential instability for more server capacity.

As always, I'm not a good C# dev, so please feel free to let me know what I should change to keep it more in-line with the project.
Oh yeah, I also didn't add comments... If it's a necessary thing, I would appreciate it if someone could help, as I suck at commenting my code :/

2023-11-06 22:05 UTC, thesprockee requested changes
Thanks for the clean pull request! It looks like a useful feature. Check my comments please.

2023-11-06 22:05 UTC, thesprockee commented on EchoRelay.Core/Server/Services/Matching/MatchingService.cs
> +                    unfilledServerOnly: false,
why does `unfilledServerOnly` get switched to false here?

2023-11-06 22:05 UTC, thesprockee commented on EchoRelay.Core/Server/Services/ServerDB/ServerDBService.cs
> +                if (apiKey != null || !Server.Settings.ServerDBAllowUnverifiedServers)
the apiKey can't be null because it's checked in the if statement on line 91. 

I suggest avoiding the nested if by changing line 91 to:

```c#
if (Server.Settings.ServerDBApiKey != null && apiKey != Server.Settings.ServerDBApiKey || !Server.Settings.ServerDBAllowUnverifiedServers)
```

2023-11-06 22:24 UTC, UnusualNorm commented on EchoRelay.Core/Server/Services/Matching/MatchingService.cs
> +                    unfilledServerOnly: false,
Copy & paste mishap, I'll fix that shortly

2023-11-06 22:27 UTC, UnusualNorm commented on EchoRelay.Core/Server/Services/ServerDB/ServerDBService.cs
> +                if (apiKey != null || !Server.Settings.ServerDBAllowUnverifiedServers)
1. apiKey can be null there, line 91 only checks if we inputted the correct api key.

2. I could do that if you insist, but I have a chronic fear of big if statements

2023-11-07 02:07 UTC, thesprockee approved these changes

2023-11-07 02:23 UTC, closed without merging

2023-11-07 02:23 UTC, thesprockee commented
merged into main! thanks!